# 1D Tensor (221226)

In [3]:
# conda install pytorch torchvision torchaudio -c pytorch


import torch

a = torch.tensor([0, 1, 2, 3, 4])
a.dtype

torch.int64

In [4]:
a.size()

torch.Size([5])

In [5]:
a.ndimension()

1

In [7]:
# 텐서 차원 변경하기

a_col = a.view(5,1)
a_col

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [8]:
a_col = a.view(-1,1)
a_col

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [11]:
# Pytorch 텐서를 Numpy로 변환하기 --> 기존의 판다스나 그래프 작업 등 가능

import numpy as np

numpy_array = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0])
torch_tensor = torch.from_numpy(numpy_array)
back_to_numpy = torch_tensor.numpy()

In [12]:
torch_tensor

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)

In [13]:
back_to_numpy

array([0., 1., 2., 3., 4., 5.])

In [14]:
# Pandas Series -> Torch Tensor

import pandas as pd

pandas_series = pd.Series([0.1, 2, 0.3, 10.1])
pandas_to_torch = torch.from_numpy(pandas_series.values)  #.values
pandas_to_torch

tensor([ 0.1000,  2.0000,  0.3000, 10.1000], dtype=torch.float64)

In [15]:
# 인덱스처럼 사용가능

new_tensor = torch.tensor([5, 2, 6, 1])
new_tensor[0]

tensor(5)

In [16]:
new_tensor[1]

tensor(2)

In [17]:
new_tensor[0].item()

5

In [18]:
new_tensor[1].item()

2

In [19]:
# 인덱싱, 슬라이싱

c = torch.tensor([20, 1, 3, 11, 1])
c

tensor([20,  1,  3, 11,  1])

In [20]:
c[0]=100
c

tensor([100,   1,   3,  11,   1])

In [21]:
d = c[1:4]
d

tensor([ 1,  3, 11])

In [22]:
c[3:5] = torch.tensor([300, 400])

In [23]:
c

tensor([100,   1,   3, 300, 400])

In [27]:
# product of 2 tensor

u = torch.tensor([1, 2])
v = torch.tensor([3, 4])

u_ = u.view(-1, 1)
v_ = v.view(-1, 1)

z = u_*v_
z

tensor([[3],
        [8]])

In [28]:
z = u*v
z

tensor([3, 8])

In [29]:
# Dot Product

z = torch.dot(u, v)
z

tensor(11)

In [30]:
z = torch.dot(u_, v_)
z

# 에러 발생

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [31]:
# Broadcasting : 모든 원소에 1을 더한다.

z = u+1
z

tensor([2, 3])

In [32]:
u

tensor([1, 2])

In [36]:
# universal functions

a = torch.tensor([1, -1, 1, -1])
max_a = a.max()
max_a

tensor(1)

In [37]:
torch.linspace(-2, 2, steps =5)

tensor([-2., -1.,  0.,  1.,  2.])

# 2D Tensor (221227)

In [39]:
X = torch.tensor([[1,2], [2,3], [4,5]])
X.shape

torch.Size([3, 2])

## Slicing

In [40]:
X[0][0]

tensor(1)

In [49]:
X[0][0].numpy()

array(1)

### dot product: AB

In [52]:
A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])
C = torch.mm(A, B)
C

tensor([[0, 2],
        [0, 2]])

In [53]:
df = pd.DataFrame({'A':[11, 33, 22],'B':[3, 3, 2]})
torch.tensor(df.values)

tensor([[11,  3],
        [33,  3],
        [22,  2]])

### Differentiation in PyTorch

In [79]:
# y(x) = x^2
# y(x=2) = 2^2

# 2로 입력하면 에러 발생, 2.0으로 입력해야 (221227)
# RuntimeError: Only Tensors of floating point and complex dtype can require gradients

x = torch.tensor(2., requires_grad=True)
y = x**2

external_grad = torch.tensor(1.)    # 문법적인 방법 (221227)
y.backward(gradient=external_grad)
#y.backward()

x.grad

tensor(4.)

In [80]:
x = torch.tensor(2., requires_grad=True)
y = x**2

y.backward()

x.grad

tensor(4.)

### Partial Derivatives

In [82]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

Q = 3*a**2 - b**2

external_grad = torch.tensor([1., 1.])   # [1., 1.] 값의 의미?
Q.backward(gradient=external_grad)

a.grad   # a 편미분 결과

tensor([12., 18.])

In [83]:
b.grad

tensor([-12.,  -8.])

In [86]:
u = torch.tensor(1., requires_grad=True)
v = torch.tensor(2., requires_grad=True)

f = u*v + u**2

f.backward()

v.grad

tensor(1.)

In [88]:
u.grad   # v+2u = 2+2(1) = 4

tensor(4.)

# Simple Dataset

In [ ]:
# Build a Data Set Class and Object
# build a Data Set Transform
# Compose Transforms

In [98]:
'''

# Define class for dataset

class toy_set(Dataset):
    
    # Constructor with defult values 
    def __init__(self, length = 100, transform = None):
        self.len = length
        self.x = 2 * torch.ones(length, 2)
        self.y = torch.ones(length, 1)
        self.transform = transform
     
    # Getter
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)     
        return sample
    
    # Get Length
    def __len__(self):
        return self.len
        
'''

In [103]:
from torch.utils.data import Dataset

# 토이 데이터셋 클래스

class toy_set(Dataset):
    def __init__(self, length=100, transform=None):
        
        self.x = 2*torch.ones(length, 2)   # self.x => [2, 2], [2, 2] .....
        self.y = torch.ones(length, 1)     # self.y => 2, 2, 2, ...
        self.len = length                  # index => 0, 1, 2, ...
        self.transform = transform
        
    def __getitem__(self, index):
        sample=self.x[index], self.y[index]   # 텐서 x, y를 sample 에 저장
        
        if self.transform:
            sample=self.transform(sample)  
        
        return sample
    
    def __len__(self):
        
        return self.len

In [104]:
dataset = toy_set()

len(dataset)

100

In [105]:
dataset[0]

(tensor([2., 2.]), tensor([1.]))

In [106]:
dataset[99]

(tensor([2., 2.]), tensor([1.]))

In [108]:
for i in range(10):
    x, y = dataset[i]
    print(i, 'x:', x, 'y:', y)

0 x: tensor([2., 2.]) y: tensor([1.])
1 x: tensor([2., 2.]) y: tensor([1.])
2 x: tensor([2., 2.]) y: tensor([1.])
3 x: tensor([2., 2.]) y: tensor([1.])
4 x: tensor([2., 2.]) y: tensor([1.])
5 x: tensor([2., 2.]) y: tensor([1.])
6 x: tensor([2., 2.]) y: tensor([1.])
7 x: tensor([2., 2.]) y: tensor([1.])
8 x: tensor([2., 2.]) y: tensor([1.])
9 x: tensor([2., 2.]) y: tensor([1.])


### Transforms

In [118]:
class add_mult(object):
    
    def __init__(self, addx=1, muly=1):  # x에 더해질 숫자, y에 곱해질 숫자 미리 선언
        self.addx=addx
        self.muly=muly
        
    def __call__(self, sample):
        x=sample[0]
        y=sample[1]
        x=x+self.addx
        y=y*self.muly
        
        sample=x,y   # 각각 계산된 x, y를 sample에 전달
        
        return sample

In [119]:
dataset=toy_set() # Transform 파라미터가 없이 선언 (None) -->  self.transform = None

# 단순히 텐서 x와 텐서 y를 얻는다  ---> return sample

a_m=add_mult()

In [121]:
# 첫번때 데이터셋을 a_m 오브젝트에 

x_, y_ = a_m(dataset[0])

# dataset[0] : ([2,2], 1)  ---> 튜플을 전달
# x: [2, 2] +1 => [3, 3]
# y: 1*1 => 1

In [116]:
x_

tensor([3., 3.])

In [117]:
y_

tensor([1.])

In [122]:
# Transform 오브젝트를 적용하면,

dataset_ = toy_set(transform=a_m)

In [123]:
# 간단히 동일한 결과를 얻을 수 있다. (221228)

dataset_[0]

(tensor([3., 3.]), tensor([1.]))

# transforms, Compose

In [ ]:
# Build a Data Set Class and Object
# Build a Data Set Transform
# Compose Transform

### Transforms compose

In [ ]:
# 기 정의된 2개의 클래스
# add_mult  : 더하기, 곱하기
# mult : 곱하기만

# 컨스트럭터를 리스트로 입력한다.

'''

from torchvision import transforms

data_transform = transforms.Compose([add_mult(), mult()])

x_, y_ = data_transform(dataset[0]) 

# add_mult() -> mult() 순으로 순차적으로 계산하여 output 출력

'''

In [ ]:
# 토이 셋에 data_transform 을 바로 적용할 수 있다.

'''

data_set_tr = toy_set(transform=data_transform)

data_set_tr[0]   # 출력 값을 확인


'''

In [125]:
# Create tranform class mult

class mult(object):
    
    # Constructor
    def __init__(self, mult = 100):
        self.mult = mult
        
    # Executor
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x * self.mult
        y = y * self.mult
        sample = x, y
        return sample

In [126]:
# torchvision 설치 방법? (221227)


from torchvision import transforms

data_transform = transforms.Compose([add_mult(), mult()])

# 기 계산 결과에서 x, y 각각에 100을 곱한 값을 출력하는지 확인 (221228)



ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/Users/wontaelee/miniforge3/lib/python3.9/site-packages/PIL/__init__.py)